ignored = ["github.com/kubeflow/xgboost-operator"]

required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
]

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "github.com/kubeflow/common"
  branch = "master"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.2"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.11.2"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.2"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.2"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false
